modLoader = "javafml"
loaderVersion = "[36,)"
license = "CC0-1.0"
issueTrackerURL="https://github.com/MrNavaStar/SQLib/issues"

[[mods]]
modId = "sqlib"
version = "0.debug-build"
displayName = "SQLib"
displayURL="https://github.com/MrNavaStar/SQLib"
logoFile="assets/sqlib/icon.png"
authors="MrNavaStar"
description = 'A simple SQL wrapper with a focus on Minecraft use cases'

displayTest="IGNORE_ALL_VERSION"