# Config File for SQLib

# Settings that apply regardless of database used
[database]
    name = "default"
    # Allowed Values: sqlite, mysql, mariadb, postgres
    type = "sqlite"

# Used for SQLite
[local]
    # Can be any path that exists on this system
    directory = "${local_path}"

# Used for MySQL, MariaDB, and Postgres
[server]
    address = "127.0.0.1"
    port = 3306
    username = "user"
    password = "pass"