on:
  push:
    tags:
      - '*'

jobs:
  modrinth:
    steps:
      - uses: Kir-Antipov/mc-publish@v3.2
        with:
          name: ""
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          files: build/libs/*.jar

          version-resolver: releases
          loaders: |
            fabric
            quilt
          java: 17